stages:

  preprocess:

    cmd: python src/preprocess_v2.py

    deps:
      - src/preprocess_v2.py
      - data/raw/loan_data.csv

    outs:
      - data/processed/processed_data_v2.csv

  train:
    cmd: python src/train_final.py

    deps:
      - src/train_final.py
      - data/processed/processed_data_v2.csv
      - params.yaml

    params:
      - train.test_size
      - train.random_state
      - model.model_type
      - logistic_regression.max_iter

    outs:
      - models/final_model.pkl
      - models/scaler.pkl
      - data/processed/test_data_v2.csv

  evaluate:

    cmd: python src/evaluate.py

    deps:
      - src/evaluate.py
      - models/final_model.pkl
      - data/processed/processed_data_v2.csv

    outs:
      - reports/final_model_metrics.json